# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push]

jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Upload a builded file.
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Push to SFTP
      uses: AbleLincoln/push-to-sftp@v1.2
      with:
              host: lvcharts.de
              port: 22
              username: root
              password: ${{ secrets.PASSWORD }}
              local-dir: ./orginal/lvc-api/
              server-dir: ./html/lib/system/lvc/
