# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on: [push]

jobs:
  upload_files:
    runs-on: ubuntu-latest
    name: Upload a builded file.
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Upload Files
      id: upload
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: 'lvcharts.de'
        port: 22
        username: 'root'
        password: '${{ secrets.PASSWORD }}'
        localPath: './orginal/lvc-api/'
        remotePath: '/var/www/html/lib/system/lvc/'
